services:
  tracking:
    image: object-tracking:jazzy

    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}

    volumes:
      - ./objtrk_ws/src/tracking_bringup/config/tracking_fake.yaml:/config/tracking.yaml:ro

    command:
      - ros2
      - launch
      - tracking_bringup
      - tracking.launch.py
      - config_file:=/config/tracking.yaml
